/*
 * Copyright 2015 LINE Corporation
 *
 * LINE Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package com.linecorp.armeria.server.avro;

import com.linecorp.armeria.internal.common.avro.AvroMessage;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.linecorp.armeria.common.CompletableRpcResponse;
import com.linecorp.armeria.common.RequestContext;
import com.linecorp.armeria.common.RpcRequest;
import com.linecorp.armeria.common.RpcResponse;
import com.linecorp.armeria.internal.common.thrift.ThriftFunction;
import com.linecorp.armeria.server.RpcService;
import com.linecorp.armeria.server.ServiceRequestContext;
import org.apache.avro.AvroRuntimeException;
import org.apache.avro.ipc.Callback;
import org.apache.thrift.*;
import org.apache.thrift.async.AsyncMethodCallback;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nullable;
import java.util.List;
import java.util.Map;

import static com.google.common.collect.ImmutableMap.toImmutableMap;
import static java.util.Objects.requireNonNull;

/**
 * An {@link RpcService} that handles a Thrift {@link RpcRequest}.
 *
 * @see AvroHttpService
 */
public final class AvroCallService implements RpcService {

    private static final Logger logger = LoggerFactory.getLogger(AvroCallService.class);

    private static final Callback<Object> ONEWAY_CALLBACK = new Callback<Object>() {
        @Override
        public void handleResult(Object result) {}

        @Override
        public void handleError(Throwable e) {
            logOneWayFunctionFailure(RequestContext.currentOrNull(), e);
        }
    };

    /**
     * Creates a new {@link AvroCallService} with the specified protocol implementation.
     *
     * @param implementation an implementation of {@code *.Iface} or {@code *.AsyncIface} service interface
     *                       generated by the Apache Avro compiler
     */
    public static AvroCallService of(Object implementation) {
        requireNonNull(implementation, "implementation");
        return new AvroCallService(ImmutableMap.of("", ImmutableList.of(implementation)));
    }

    /**
     * Creates a new multiplexed {@link AvroCallService} with the specified list service implementations.
     *
     * @param implementations a {@link Map} whose key is service name and value is the list of implementations
     *                        of {@code *.Iface} or {@code *.AsyncIface} service interface generated by
     *                        the Apache Avro compiler
     */
    public static AvroCallService of(Map<String, ? extends Iterable<?>> implementations) {
        requireNonNull(implementations, "implementations");
        return new AvroCallService(implementations);
    }

    private final Map<String, AvroServiceEntry> entries;

    private AvroCallService(Map<String, ? extends Iterable<?>> implementations) {
        requireNonNull(implementations, "implementations");
        if (implementations.isEmpty()) {
            throw new IllegalArgumentException("empty implementations");
        }

        entries = implementations.entrySet().stream().collect(
                toImmutableMap(Map.Entry::getKey, AvroServiceEntry::new));
    }

    /**
     * Returns the information about the Avro protocols being served.
     *
     * @return a {@link Map} whose key is a service name, which could be an empty string if this service
     *         is not multiplexed
     */
    public Map<String, AvroServiceEntry> entries() {
        return entries;
    }

    @Override
    public RpcResponse serve(ServiceRequestContext ctx, RpcRequest call) throws Exception {
        final int colonPos = call.method().indexOf(':');
        final String method;
        final String serviceName;
        if (colonPos < 0) {
            serviceName = "";
            method = call.method();
        } else {
            serviceName = call.method().substring(0, colonPos);
            method = call.method().substring(colonPos + 1);
        }

        // Ensure that such a service exists.
        final AvroServiceEntry e = entries.get(serviceName);
        if (e != null) {
            // Ensure that such a method exists.
            final AvroMessage f = e.metadata.function(method);
            if (f != null) {
                if (f.implementation() != null) {
                    final CompletableRpcResponse reply = new CompletableRpcResponse();
                    invoke(ctx, f.implementation(), f, call.params(), reply);
                    return reply;
                }
                // Should never reach here because of the way ThriftServiceEntry is created
                return RpcResponse.ofFailure(new AvroRuntimeException(
                        TApplicationException.UNKNOWN, "null implementation: " + call.method()));
            }
        }
        return RpcResponse.ofFailure(new AvroRuntimeException(
                TApplicationException.UNKNOWN_METHOD, "unknown method: " + call.method()));
    }

    private static void invoke(
            ServiceRequestContext ctx,
            Object impl, AvroMessage func, List<Object> args, CompletableRpcResponse reply) {

        try {
            final TBase<?, ?> tArgs = func.newArgs(args);
            if (func.isAsync()) {
                invokeAsynchronously(impl, func, tArgs, reply);
            } else {
                invokeSynchronously(ctx, impl, func, tArgs, reply);
            }
        } catch (Throwable t) {
            reply.completeExceptionally(t);
        }
    }

    private static void invokeAsynchronously(Object impl, AvroMessage func, TBase<?, ?> args,
                                             CompletableRpcResponse reply) throws AvroRuntimeException {

        final AsyncProcessFunction<Object, TBase<?, ?>, Object> f = func.asyncFunc();
        if (func.isOneWay()) {
            f.start(impl, args, ONEWAY_CALLBACK);
            reply.complete(null);
        } else {
            f.start(impl, args, new Callback<Object>() {
                @Override
                public void handleResult(Object response) {
                    reply.complete(response);
                }

                @Override
                public void handleError(Throwable e) {
                    reply.completeExceptionally(e);
                }
            });
        }
    }

    private static void invokeSynchronously(
            ServiceRequestContext ctx, Object impl,
            ThriftFunction func, TBase<?, ?> args, CompletableRpcResponse reply) {

        final ProcessFunction<Object, TBase<?, ?>> f = func.syncFunc();
        ctx.blockingTaskExecutor().execute(() -> {
            if (reply.isDone()) {
                // Closed already most likely due to timeout.
                return;
            }

            try {
                if (func.isOneWay()) {
                    reply.complete(null);
                    f.getResult(impl, args);
                } else {
                    final TBase<?, ?> result = f.getResult(impl, args);
                    reply.complete(func.getResult(result));
                }
            } catch (Throwable t) {
                if (func.isOneWay()) {
                    reply.complete(null);
                    logOneWayFunctionFailure(ctx, t);
                } else {
                    reply.completeExceptionally(t);
                }
            }
        });
    }

    private static void logOneWayFunctionFailure(@Nullable RequestContext ctx, Throwable cause) {
        if (ctx != null) {
            logger.warn("{} Unexpected exception from a one-way function:", ctx, cause);
        } else {
            // Should never reach here, but for completeness.
            logger.warn("Unexpected exception from a one-way function:", cause);
        }
    }
}
